apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: analytics-hachiai-tls
  namespace: superset
spec:
  secretName: analytics-hachiai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - analytics.hachiai.com

